name: Build container

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1

    permissions:
      contents: read
      packages: write
      id-token: write

    with:
      output: image
      push: true

      platforms: linux/amd64,linux/arm64

      context: ./mpi-demo
      file: ./Containerfile

      cache: true
      cache-scope: mpi-demo

      meta-images: ghcr.io/felipecr/mpi-demo
      meta-tags: |
        type=raw,value=latest
        type=sha

    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
